app:
  key: 'abcdefgklmnoprst'

database:
  host: localhost
  port: 5432
  username: postgres
  password: 1234567890
  db_name: postgres

#database:
#  host: 89.108.103.170
#  port: 5432
#  username: fsrar_user
#  password: Qwerty1234
#  db_name: conductor



